# Generated by Django 4.2.7 on 2023-12-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0003_alter_clothes_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothes",
            name="store",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.DeleteModel(
            name="Stores",
        ),
    ]
