# Generated by Django 4.2.7 on 2023-12-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0004_alter_clothes_store_delete_stores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clothe_colors",
            name="clothes",
        ),
        migrations.RemoveField(
            model_name="clothe_colors",
            name="colors",
        ),
        migrations.AddField(
            model_name="clothe_colors",
            name="clothe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clothe_color",
                to="boards.clothes",
            ),
        ),
        migrations.AddField(
            model_name="clothe_colors",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clothe_colors",
                to="boards.colors",
            ),
        ),
        migrations.AlterField(
            model_name="clothes",
            name="color",
            field=models.ManyToManyField(
                related_name="clothe",
                through="boards.Clothe_Colors",
                to="boards.colors",
            ),
        ),
    ]
