# Generated by Django 4.2.7 on 2024-01-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0006_alter_clothe_colors_clothe_alter_clothe_colors_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothes",
            name="price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
