# Generated by Django 4.2.7 on 2024-01-01 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0007_alter_clothes_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clothes",
            old_name="purchase_data",
            new_name="purchase_date",
        ),
        migrations.AlterField(
            model_name="clothe_colors",
            name="clothe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clothe_relation",
                to="boards.clothes",
            ),
        ),
        migrations.AlterField(
            model_name="clothe_colors",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color_relation",
                to="boards.colors",
            ),
        ),
    ]
