# Generated by Django 4.2.7 on 2024-01-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "boards",
            "0010_alter_clothe_colors_clothe_alter_clothe_colors_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothes",
            name="color",
            field=models.ManyToManyField(
                blank=True,
                related_name="clothe",
                through="boards.Clothe_Colors",
                to="boards.colors",
            ),
        ),
    ]
