# Generated by Django 4.2.7 on 2023-12-27 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_users_managers_users_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
    ]
