# Generated by Django 4.2.7 on 2024-02-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothes",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
