# Generated by Django 4.2.7 on 2024-02-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0002_alter_clothes_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothes",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="closet_project/media/"
            ),
        ),
    ]
